require: umts-custom-cops

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'Guardfile'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 11

Rails/Date:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/SignalException:
  Enabled: false
